version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  build:
    commands:
      - echo "Current directory:"
      - pwd
      - echo "Listing files:"
      - ls -la

artifacts:
  files:
    - lambda.zip
    - cloudformation/lambda-stack.yaml
