AWSTemplateFormatVersion: "2010-09-09"
Description: CodePipeline to build and deploy Lambda using CloudFormation

Parameters:
  SourceBucket:
    Type: String
    Description: S3 bucket where source.zip is uploaded (must be versioned)

  ArtifactBucket:
    Type: String
    Description: S3 bucket for CodePipeline artifacts

Resources:

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: codepipeline-service-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:

              # Read source from S3
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                Resource:
                  - !Sub arn:aws:s3:::${SourceBucket}
                  - !Sub arn:aws:s3:::${SourceBucket}/*

              # Write artifacts to artifact bucket
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub arn:aws:s3:::${ArtifactBucket}/*

              # Trigger CodeBuild
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                Resource: !GetAtt LambdaBuildProject.Arn

              # CloudFormation deploy permissions (CHANGESETS INCLUDED)
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:GetTemplateSummary
                  - cloudformation:CreateChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DeleteChangeSet
                Resource: "*"

              # Allow passing CF execution role
              - Effect: Allow
                Action: iam:PassRole
                Resource: !GetAtt CloudFormationExecutionRole.Arn

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: codebuild-service-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # Logs
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

              # Read source + upload artifacts
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub arn:aws:s3:::${SourceBucket}/*
                  - !Sub arn:aws:s3:::${ArtifactBucket}/*

  CloudFormationExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cloudformation-execution-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudFormationExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:*
                  - iam:*
                  - ssm:*
                  - logs:*
                  - cloudformation:*
                  - s3:*
                Resource: "*"

  LambdaBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: lambda-build-project
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
      Source:
        Type: CODEPIPELINE

  LambdaPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: lambda-deployment-pipeline
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:

        # ---------- SOURCE ----------
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: "1"
              Configuration:
                S3Bucket: !Ref SourceBucket
                S3ObjectKey: source.zip
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: SourceOutput

        # ---------- BUILD ----------
        - Name: Build
          Actions:
            - Name: BuildLambda
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref LambdaBuildProject

        # ---------- DEPLOY ----------
        - Name: Deploy
            Actions:
              - Name: DeployLambda
                ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: CloudFormation
                  Version: "1"
                InputArtifacts:
                  - Name: BuildOutput
                Configuration:
                  ActionMode: CREATE_UPDATE
                  StackName: ssm-lambda-stack
                  Capabilities: CAPABILITY_NAMED_IAM
                  TemplatePath: BuildOutput::cloudformation/lambda-stack.yaml
                  RoleArn: arn:aws:iam::4604-4298-2907:role/cloudformation-execution-role
                  


