AWSTemplateFormatVersion: "2010-09-09"
Description: CodePipeline to build and deploy Lambda using CloudFormation

Parameters:
  SourceBucket:
    Type: String
    Description: S3 bucket where source.zip is uploaded (must be versioned for S3 Source action)

  ArtifactBucket:
    Type: String
    Description: S3 bucket for CodePipeline artifacts

Resources:
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # Read source.zip from SourceBucket
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                Resource:
                  - !Sub "arn:aws:s3:::${SourceBucket}"
                  - !Sub "arn:aws:s3:::${SourceBucket}/*"

              # Read/write artifacts to ArtifactBucket
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                Resource:
                  - !Sub "arn:aws:s3:::${ArtifactBucket}/*"

              # Allow pipeline to run CodeBuild
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                Resource: !GetAtt LambdaBuildProject.Arn

              # Allow pipeline to call CloudFormation for the deploy action
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:GetTemplateSummary
                Resource: "*"

              # IMPORTANT: allow CodePipeline to pass the execution role to CloudFormation
              - Effect: Allow
                Action: iam:PassRole
                Resource: !GetAtt CloudFormationExecutionRole.Arn

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

              # If you ever switch CodeBuild artifacts from CODEPIPELINE to S3,
              # you'll need S3 permissions here; leaving minimal for now.

  CloudFormationExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudFormationExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # For assessment speed this is permissive; tighten to least-privilege after it works.
              - Effect: Allow
                Action: "*"
                Resource: "*"

  LambdaBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: lambda-build-project
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
      Source:
        Type: CODEPIPELINE

  LambdaPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: lambda-deployment-pipeline
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
            Actions:
              - Name: SourceAction
                RoleArn: !GetAtt CodePipelineRole.Arn
                ActionTypeId:
                  Category: Source
                  Owner: AWS
                  Provider: S3
                  Version: "1"
                Configuration:
                  S3Bucket: !Ref SourceBucket
                  S3ObjectKey: source.zip
                  PollForSourceChanges: true
                OutputArtifacts:
                  - Name: SourceOutput

        - Name: Build
          Actions:
            - Name: BuildLambda
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref LambdaBuildProject

        - Name: Deploy
          Actions:
            - Name: DeployLambda
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: ssm-lambda-stack
                Capabilities: CAPABILITY_NAMED_IAM
                TemplatePath: BuildOutput::cloudFormation/lambda-stack.yaml
                RoleArn: !GetAtt CloudFormationExecutionRole.Arn
